# Generated by Django 5.0.3 on 2024-04-07 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Avatar', 'verbose_name_plural': 'Avatars'},
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='pofile picture.png', upload_to='avatars/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
